<template><div class="chat-stack" :style="{width:(widget.data.width||400)+'px'}"><transition-group name="chat"><div v-for="(msg,index) in visibleMessages" :key="msg.id" class="message" :class="[msg.platform,{older:index>0}]" :style="messageStyle(index)"><div v-if="widget.data.showIcons!==false" class="avatar"><i :class="msg.platform==='tiktok'?'fab fa-tiktok':'fab fa-twitch'"></i></div><div class="copy"><strong>{{ msg.user }}</strong><span>{{ msg.text }}</span></div><span class="shine">+</span></div></transition-group></div></template>
<script setup>
import {computed,onMounted,onUnmounted,ref} from 'vue';import tmi from 'tmi.js';import {socket} from '@/services/socket'
const props=defineProps({widget:Object});const isEditor=window.location.pathname.includes('editor');let twitchClient
const messages=ref(isEditor?[{id:'preview1',user:'usuario',text:'Mensaje de prueba',platform:'twitch'},{id:'preview2',user:'otro',text:'Se vera asi en directo',platform:'tiktok'}]:[])
const visibleMessages=computed(()=>messages.value.slice(0,Number(props.widget.data.messageLimit)||4))
const addMessage=msg=>{messages.value.unshift(msg);if(messages.value.length>8)messages.value.pop()}
const messageStyle=index=>({fontSize:Math.max((props.widget.data.fontSize||18)-(index?3:0),11)+'px',color:props.widget.data.textColor||'#fff',background:`radial-gradient(circle at 92% 0, rgba(168,85,247,.3), transparent 34%), ${props.widget.data.bgColor||'#17102f'}`,borderWidth:(props.widget.data.borderWidth??1)+'px',borderColor:props.widget.data.borderColor||'#a855f7',borderRadius:props.widget.data.rounded===false?'8px':'18px'})
const onTikTokMessage=msg=>{if(msg.platform==='tiktok')addMessage({id:Date.now(),user:msg.user,text:msg.text,platform:'tiktok'})}
onMounted(()=>{if(isEditor)return;const platform=props.widget.data.platform||'both';if(platform!=='tiktok'&&props.widget.data.channel){twitchClient=new tmi.Client({connection:{secure:true,reconnect:true},channels:[props.widget.data.channel]});twitchClient.connect();twitchClient.on('message',(channel,tags,message)=>addMessage({id:Date.now(),user:tags.username,text:message,platform:'twitch'}))}const user=props.widget.data.tiktokUser||'';if(platform!=='twitch'&&user&&socket){socket.emit('joinTikTok',user);socket.on('message',onTikTokMessage)}})
onUnmounted(()=>{twitchClient?.disconnect?.();socket?.off?.('message',onTikTokMessage)})
</script>
<style scoped>
.chat-stack{display:flex;flex-direction:column;gap:9px}.chat-stack .message{position:relative;overflow:hidden;display:flex;align-items:center;gap:11px;padding:12px 15px;border-style:solid;box-shadow:0 12px 30px rgba(5,2,18,.34),inset 0 1px rgba(255,255,255,.09);backdrop-filter:blur(10px);transition:.3s}.chat-stack .message.twitch{border-left:4px solid #a970ff!important}.chat-stack .message.tiktok{border-left:4px solid #ff2d78!important}.chat-stack .message.older{opacity:.72;transform:scale(.96);transform-origin:left}.chat-stack .avatar{flex:0 0 34px;width:34px;height:34px;border-radius:10px;display:grid;place-items:center;color:white;background:linear-gradient(145deg,#7c3aed,#db2777);box-shadow:0 0 16px rgba(192,38,211,.35)}.chat-stack .copy{min-width:0;display:flex;flex-direction:column;line-height:1.25}.chat-stack .copy strong{font-size:.78em;color:#e9d5ff}.chat-stack .copy span{overflow-wrap:anywhere;font-weight:650;color:inherit}.chat-stack .shine{position:absolute;right:10px;top:5px;color:white;text-shadow:0 0 8px white}.chat-enter-active,.chat-leave-active{transition:.3s}.chat-enter-from{opacity:0;transform:translateY(18px)}.chat-leave-to{opacity:0;transform:translateY(-18px)}
</style>
