<template><div><button v-if="isMinimized" class="mission-bubble" :style="bubbleStyle" @click="toggle"><span class="orbit"></span><i :class="bubbleIcon"></i><strong>{{ done }}/{{ total }}</strong></button><transition name="panel"><div v-if="!isMinimized" class="mission-card" :style="cardStyle"><span class="star">+</span><header><div><small>MISIONES DE LA GALAXIA</small><h3>Misiones</h3></div><button @click="toggle" title="Minimizar"><i class="fas fa-minus"></i></button></header><div class="progress"><span :style="{width:(progress*100)+'%'}"></span></div><div class="tasks"><button v-for="(task,index) in widget.data.tasks" :key="index" class="task" :class="{done:task.done}" @click="toggleTask(index)"><span class="check"><i v-if="task.done" class="fas fa-check"></i></span><span>{{ task.text }}</span></button></div><footer>{{ done }} DE {{ total }} COMPLETADAS</footer></div></transition></div></template>
<script setup>
import {computed,onMounted,ref,watch} from 'vue'
const props=defineProps({widget:Object});const isMinimized=ref(false)
onMounted(()=>{const d=props.widget.data;d.tasks??=[{text:'Nueva mision',done:false}];d.bgColor??='#17102f';d.textColor??='#fff';d.fontSize??=16;d.bubbleColor??='#9333ea';d.bubbleSize??=70;d.width??=340;d.icon??='fa-solid fa-star';isMinimized.value=d.minimized??false})
const toggle=()=>{isMinimized.value=!isMinimized.value;props.widget.data.minimized=isMinimized.value};const toggleTask=i=>props.widget.data.tasks[i].done=!props.widget.data.tasks[i].done
const total=computed(()=>props.widget.data.tasks.length);const done=computed(()=>props.widget.data.tasks.filter(t=>t.done).length);const progress=computed(()=>total.value?done.value/total.value:0)
watch(progress,v=>{if(v===1)setTimeout(()=>{isMinimized.value=true;props.widget.data.minimized=true},1200)})
watch(()=>props.widget.data.minimized,value=>{isMinimized.value=Boolean(value)})
const bubbleStyle=computed(()=>({width:(props.widget.data.bubbleSize||70)+'px',height:(props.widget.data.bubbleSize||70)+'px','--accent':props.widget.data.bubbleColor||'#9333ea'}));const cardStyle=computed(()=>({width:(props.widget.data.width||340)+'px',color:props.widget.data.textColor||'#fff',background:`radial-gradient(circle at 100% 0, rgba(217,70,239,.32), transparent 38%), ${props.widget.data.bgColor||'#17102f'}`,'--accent':props.widget.data.bubbleColor||'#9333ea',fontSize:(props.widget.data.fontSize||16)+'px'}));const bubbleIcon=computed(()=>progress.value===1?'fa-solid fa-crown':progress.value>.5?'fa-solid fa-bolt':props.widget.data.icon)
</script>
<style scoped>
.mission-bubble{position:relative;border:1px solid rgba(255,255,255,.38);border-radius:50%;color:white;background:radial-gradient(circle at 35% 28%,#d8b4fe,var(--accent) 48%,#4c1d95);box-shadow:0 0 14px var(--accent),0 14px 30px rgba(8,3,24,.45);display:grid;place-items:center;cursor:pointer}.mission-bubble i{font-size:25px;filter:drop-shadow(0 0 6px white)}.mission-bubble strong{position:absolute;right:-5px;bottom:-3px;padding:3px 6px;border-radius:9px;background:#17102f;color:white;font-size:9px}.orbit{position:absolute;inset:7px;border:1px dashed rgba(255,255,255,.42);border-radius:50%;animation:spin 8s linear infinite}.mission-card{position:relative;overflow:hidden;padding:19px;border:1px solid var(--accent);border-radius:22px;box-shadow:0 18px 44px rgba(8,3,24,.4),inset 0 1px rgba(255,255,255,.11)}.mission-card header{display:flex;justify-content:space-between;align-items:center}.mission-card header small,.mission-card footer{font-size:9px;letter-spacing:1.1px;font-weight:900;color:#c4b5fd}.mission-card h3{margin:2px 0 9px;font-size:1.2em;font-weight:900;color:inherit}.mission-card header button{width:27px;height:27px;border-radius:8px;color:white;background:rgba(255,255,255,.1)}.mission-card .progress{height:5px;border-radius:99px;background:rgba(255,255,255,.12);overflow:hidden;margin-bottom:12px}.mission-card .progress span{display:block;height:100%;background:linear-gradient(90deg,#8b5cf6,var(--accent));box-shadow:0 0 10px var(--accent)}.mission-card .tasks{display:flex;flex-direction:column;gap:8px}.mission-card .task{display:flex;align-items:center;gap:9px;text-align:left;font-weight:700;width:100%;color:inherit;background:transparent}.mission-card .task.done{opacity:.48;text-decoration:line-through}.mission-card .check{flex:0 0 21px;width:21px;height:21px;border:1px solid #c4b5fd;border-radius:7px;display:grid;place-items:center;color:white;background:rgba(255,255,255,.06);font-size:10px}.mission-card .task.done .check{background:var(--accent);box-shadow:0 0 9px var(--accent)}.mission-card footer{text-align:right;margin-top:13px}.star{position:absolute;right:65px;top:18px;color:white;text-shadow:0 0 8px white;animation:twinkle 2s infinite}.panel-enter-active,.panel-leave-active{transition:.25s}.panel-enter-from,.panel-leave-to{opacity:0;transform:scale(.92)}@keyframes spin{to{transform:rotate(360deg)}}@keyframes twinkle{50%{opacity:.2;transform:scale(.6)}}
</style>
